<?php

use App\Models\Role;

return [
    [
        'name' => 'BCA KCU Denpasar',
        'address' => 'Jl. Hasanuddin No.58, Pemecutan, Kec. Denpasar Bar., Kota Denpasar, Bali 80232',
        'users' => [
            [
                'username' => 'manager_denpasar',
                'name' => 'Manager Denpasar',
                'email' => 'manager_denpasar@manager.com',
                'password' => 'manager_denpasar12345',
                'is_verified' => true,
                'role' => Role::ROLE_MANAGER,
            ],
            [
                'username' => 'staff_denpasar',
                'name' => 'Staff Denpasar',
                'email' => 'staff_denpasar@staff.com',
                'password' => 'staff_denpasar12345',
                'is_verified' => true,
                'role' => Role::ROLE_STAFF,
            ],
        ],
    ],
    [
        'name' => 'BCA KCP Cokroaminoto',
        'address' => 'Pemecutan Kaja, North Denpasar, Denpasar City, Bali',
        'users' => [
            [
                'username' => 'manager_cokroaminoto',
                'name' => 'Manager Cokroaminoto',
                'email' => 'manager_cokroaminoto@manager.com',
                'password' => 'manager_cokroaminoto12345',
                'is_verified' => true,
                'role' => Role::ROLE_MANAGER,
            ],
            [
                'username' => 'staff_cokroaminoto',
                'name' => 'Staff Cokroaminoto',
                'email' => 'staff_cokroaminoto@staff.com',
                'password' => 'staff_cokroaminoto12345',
                'is_verified' => true,
                'role' => Role::ROLE_STAFF,
            ],
        ],
    ],
    [
        'name' => 'BCA KCP Gatot Subroto Barat',
        'address' => 'Jl. Gatot Subroto Barat No.508-509, Padangsambian Kaja, Kec. Denpasar Bar., Kota Denpasar, Bali 80117',
        'users' => [
            [
                'username' => 'manager_gatsubarat',
                'name' => 'Manager Gatot Subroto Barat',
                'email' => 'manager_gatsubarat@manager.com',
                'password' => 'manager_gatsubarat12345',
                'is_verified' => true,
                'role' => Role::ROLE_MANAGER,
            ],
            [
                'username' => 'staff_gatsubarat',
                'name' => 'Staff Gatot Subroto Barat',
                'email' => 'staff_gatsubarat@staff.com',
                'password' => 'staff_gatsubarat12345',
                'is_verified' => true,
                'role' => Role::ROLE_STAFF,
            ],
        ],
    ],
    [
        'name' => 'BCA KCP Gatot Subroto',
        'address' => 'Jl. Gatot Subroto Barat No.80, Dangin Puri Kaja, Kec. Denpasar Utara, Kota Denpasar, Bali 80234',
        'users' => [
            [
                'username' => 'manager_gatsu',
                'name' => 'Manager Gatot Subroto',
                'email' => 'manager_gatsu@manager.com',
                'password' => 'manager_gatsu12345',
                'is_verified' => true,
                'role' => Role::ROLE_MANAGER,
            ],
            [
                'username' => 'staff_gatsu',
                'name' => 'Staff Gatot Subroto',
                'email' => 'staff_gatsu@staff.com',
                'password' => 'staff_gatsu12345',
                'is_verified' => true,
                'role' => Role::ROLE_STAFF,
            ],
        ],
    ],
    [
        'name' => 'BCA KCP Gatot Subroto Timur',
        'address' => 'Jl. Gatot Subroto Tim. No.42- 43, Kesiman Kertalangu, Kec. Denpasar Tim., Kota Denpasar, Bali 80237',
        'users' => [
            [
                'username' => 'manager_gatsutimur',
                'name' => 'Manager Gatot Subroto Timur',
                'email' => 'manager_gatsutimur@manager.com',
                'password' => 'manager_gatsutimur12345',
                'is_verified' => true,
                'role' => Role::ROLE_MANAGER,
            ],
            [
                'username' => 'staff_gatsutimur',
                'name' => 'Staff Gatot Subroto Timur',
                'email' => 'staff_gatsutimur@staff.com',
                'password' => 'staff_gatsutimur12345',
                'is_verified' => true,
                'role' => Role::ROLE_STAFF,
            ],
        ],
    ],
    [
        'name' => 'BCA KCP Gianyar',
        'address' => 'Jl. By Pass Dharma Giri, Gianyar, Kec. Gianyar, Kabupaten Gianyar, Bali 80511',
        'users' => [
            [
                'username' => 'manager_gianyar',
                'name' => 'Manager Gianyar',
                'email' => 'manager_gianyar@manager.com',
                'password' => 'manager_gianyar12345',
                'is_verified' => true,
                'role' => Role::ROLE_MANAGER,
            ],
            [
                'username' => 'staff_gianyar',
                'name' => 'Staff Gianyar',
                'email' => 'staff_gianyar@staff.com',
                'password' => 'staff_gianyar12345',
                'is_verified' => true,
                'role' => Role::ROLE_STAFF,
            ],
        ],
    ],
    [
        'name' => 'BCA KCP Klungkung',
        'address' => 'Jl. Puputan Galiran No.88C, Semarapura Kelod, Kec. Klungkung, Kabupaten Klungkung, Bali 80715',
        'users' => [
            [
                'username' => 'manager_klungkung',
                'name' => 'Manager Klungkung',
                'email' => 'manager_klungkung@manager.com',
                'password' => 'manager_klungkung12345',
                'is_verified' => true,
                'role' => Role::ROLE_MANAGER,
            ],
            [
                'username' => 'staff_klungkung',
                'name' => 'Staff Klungkung',
                'email' => 'staff_klungkung@staff.com',
                'password' => 'staff_klungkung12345',
                'is_verified' => true,
                'role' => Role::ROLE_STAFF,
            ],
        ],
    ],
    [
        'name' => 'BCA KCP Mahendradata',
        'address' => 'Jl. Mahendradatta No.99, Pemecutan Kaja, Kec. Denpasar Utara, Kota Denpasar, Bali 80111',
        'users' => [
            [
                'username' => 'manager_mahendradata',
                'name' => 'Manager Mahendradata',
                'email' => 'manager_mahendradata@manager.com',
                'password' => 'manager_mahendradata12345',
                'is_verified' => true,
                'role' => Role::ROLE_MANAGER,
            ],
            [
                'username' => 'staff_mahendradata',
                'name' => 'Staff Mahendradata',
                'email' => 'staff_mahendradata@staff.com',
                'password' => 'staff_mahendradata12345',
                'is_verified' => true,
                'role' => Role::ROLE_STAFF,
            ],
        ],
    ],
    [
        'name' => 'BCA KCP Renon',
        'address' => 'Jl. Raya Puputan No.10, Sumerta Kelod, Kec. Denpasar Tim., Kota Denpasar, Bali 80239',
        'users' => [
            [
                'username' => 'manager_renon',
                'name' => 'Manager Renon',
                'email' => 'manager_renon@manager.com',
                'password' => 'manager_renon12345',
                'is_verified' => true,
                'role' => Role::ROLE_MANAGER,
            ],
            [
                'username' => 'staff_renon',
                'name' => 'Staff Renon',
                'email' => 'staff_renon@staff.com',
                'password' => 'staff_renon12345',
                'is_verified' => true,
                'role' => Role::ROLE_STAFF,
            ],
        ],
    ],
    [
        'name' => 'BCA KCP Sesetan',
        'address' => 'Jl. Raya Sesetan, Sesetan, Denpasar Selatan, Kota Denpasar, Bali 80223',
        'users' => [
            [
                'username' => 'manager_sesetan',
                'name' => 'Manager Sesetan',
                'email' => 'manager_sesetan@manager.com',
                'password' => 'manager_sesetan12345',
                'is_verified' => true,
                'role' => Role::ROLE_MANAGER,
            ],
            [
                'username' => 'staff_sesetan',
                'name' => 'Staff Sesetan',
                'email' => 'staff_sesetan@staff.com',
                'password' => 'staff_sesetan12345',
                'is_verified' => true,
                'role' => Role::ROLE_STAFF,
            ],
        ],
    ],
    [
        'name' => 'BCA KCP Ubud',
        'address' => 'Jl. Raya Ubud No.10X, Petulu, Kecamatan Ubud, Kabupaten Gianyar, Bali 80571',
        'users' => [
            [
                'username' => 'manager_ubud',
                'name' => 'Manager Ubud',
                'email' => 'manager_ubud@manager.com',
                'password' => 'manager_ubud12345',
                'is_verified' => true,
                'role' => Role::ROLE_MANAGER,
            ],
            [
                'username' => 'staff_ubud',
                'name' => 'Staff Ubud',
                'email' => 'staff_ubud@staff.com',
                'password' => 'staff_ubud12345',
                'is_verified' => true,
                'role' => Role::ROLE_STAFF,
            ],
        ],
    ],
    [
        'name' => 'BCA KCP Grand Sudirman',
        'address' => 'Jl. PB Sudirman Blok C5-C6 Ruko Grand Sudirman, Dauh Puri Klod, Kec. Denpasar Bar., Kota Denpasar, Bali 80232',
        'users' => [
            [
                'username' => 'manager_grandsudirman',
                'name' => 'Manager Grand Sudirman',
                'email' => 'manager_grandsudirman@manager.com',
                'password' => 'manager_grandsudirman12345',
                'is_verified' => true,
                'role' => Role::ROLE_MANAGER,
            ],
            [
                'username' => 'staff_grandsudirman',
                'name' => 'Staff Grand Sudirman',
                'email' => 'staff_grandsudirman@staff.com',
                'password' => 'staff_grandsudirman12345',
                'is_verified' => true,
                'role' => Role::ROLE_STAFF,
            ],
        ],
    ],
    [
        'name' => 'BCA KCP Maluku',
        'address' => 'Jl. Pulau Maluku III No.10, Dauh Puri, Kec. Denpasar Bar., Kota Denpasar, Bali 80232',
        'users' => [
            [
                'username' => 'manager_maluku',
                'name' => 'Manager Maluku',
                'email' => 'manager_maluku@manager.com',
                'password' => 'manager_maluku12345',
                'is_verified' => true,
                'role' => Role::ROLE_MANAGER,
            ],
            [
                'username' => 'staff_maluku',
                'name' => 'Staff Maluku',
                'email' => 'staff_maluku@staff.com',
                'password' => 'staff_maluku12345',
                'is_verified' => true,
                'role' => Role::ROLE_STAFF,
            ],
        ],
    ],
    [
        'name' => 'BCA KCP Teuku Umar',
        'address' => 'Jl. Teuku Umar No.99 D, Dauh Puri Klod, Kec. Denpasar Bar., Kota Denpasar, Bali 80114',
        'users' => [
            [
                'username' => 'manager_teukuumar',
                'name' => 'Manager Teuku Umar',
                'email' => 'manager_teukuumar@manager.com',
                'password' => 'manager_teukuumar12345',
                'is_verified' => true,
                'role' => Role::ROLE_MANAGER,
            ],
            [
                'username' => 'staff_teukuumar',
                'name' => 'Staff Teuku Umar',
                'email' => 'staff_teukuumar@staff.com',
                'password' => 'staff_teukuumar12345',
                'is_verified' => true,
                'role' => Role::ROLE_STAFF,
            ],
        ],
    ],
    [
        'name' => 'BCA KCP Benoa',
        'address' => 'Jl. Suwung Batan Kendal No.2, Sesetan, Denpasar Selatan, Kota Denpasar, Bali 80222',
        'users' => [
            [
                'username' => 'manager_benoa',
                'name' => 'Manager Benoa',
                'email' => 'manager_benoa@manager.com',
                'password' => 'manager_benoa12345',
                'is_verified' => true,
                'role' => Role::ROLE_MANAGER,
            ],
            [
                'username' => 'staff_benoa',
                'name' => 'Staff Benoa',
                'email' => 'staff_benoa@staff.com',
                'password' => 'staff_benoa12345',
                'is_verified' => true,
                'role' => Role::ROLE_STAFF,
            ],
        ],
    ],
];
